language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - cp .env.travis .env
  - mysql -e 'create database forge;'
  - composer install --no-interaction -dev
  - php artisan migrate

script: ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

notifications:
  on_success: never
  on_failure: always
